M48
; DRILL file {KiCad (6.0.4)} date Mon Oct 16 18:27:47 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-16T18:27:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X101.854Y-5.588
X101.854Y-25.908
X145.034Y-5.588
X145.034Y-25.908
T0
M30
